yarn add -SE d3-scale
yarn add -SE d3-shape
yarn add -SE d3-svg-legend
yarn add -SE d3-array
yarn add -SE d3-geo
yarn add -SE d3-selection
yarn add -SE d3-transition
yarn add -SE d3-brush
yarn add -SE d3-axis